spring.application.name=fc-assets

# Connexion to PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/assets_db
spring.datasource.username=assets_user
spring.datasource.password=motdepasse
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
